# -*- coding: utf-8 -*-
"""
Created on Sun Aug  2 12:28:08 2026

@author: tarun
"""

start_date="2020-01-01"
dist_low=2
dist_high=5
money=1000000
max_positions=7
allocation_per_stock=200000
stoploss=7.5
initial_capital=1000000
first_day=70

#nifty
# TICKERS = ['TATACONSUM.NS','BAJFINANCE.NS','WIPRO.NS','ASIANPAINT.NS','HINDALCO.NS',
# 'CIPLA.NS','ETERNAL.NS','APOLLOHOSP.NS','DRREDDY.NS','SHRIRAMFIN.NS',
# 'BHARTIARTL.NS','HDFCLIFE.NS','TRENT.NS','EICHERMOT.NS','NESTLEIND.NS',
# 'INDIGO.NS','HDFCBANK.NS','RELIANCE.NS','SUNPHARMA.NS','BAJAJFINSV.NS',
# 'MAXHEALTH.NS','M&M.NS','MARUTI.NS','TITAN.NS','BAJAJ-AUTO.NS','ADANIPORTS.NS',
# 'SBILIFE.NS','SBIN.NS','ADANIENT.NS','POWERGRID.NS','JIOFIN.NS','HCLTECH.NS',
# 'HINDUNILVR.NS','JSWSTEEL.NS','TCS.NS','COALINDIA.NS','INFY.NS','ICICIBANK.NS',
# 'ITC.NS','AXISBANK.NS','ULTRACEMCO.NS','ONGC.NS','BEL.NS','NTPC.NS','KOTAKBANK.NS']

#good stocks
TICKERS=['ACE.NS', 'APCOTEXIND.NS', 'APTUS.NS', 'ASHAPURMIN.NS', 'BALUFORGE.NS', 'BANCOINDIA.NS', 'BLS.NS', 'BORORENEW.NS', 'BSE.NS', 'CHENNPETRO.NS', 'CRAMC.NS', 'CARRARO.NS', 'CEATLTD.NS', 'CEMPRO.NS', 'CHALET.NS', 'COROMANDEL.NS', 'CRIZAC.NS', 'DPABHUSHAN.NS', 'DEEPINDS.NS', 'DIXON.NS', 'EMMVEE.NS', 'EIEL.NS', 'EPIGRAL.NS', 'FINEORG.NS', 'FORCEMOT.NS', 'UTLSOLAR.NS', 'GALLANTT.NS', 'GANESHHOU.NS', 'GRSE.NS', 'GENUSPOWER.NS', 'EBGNG.NS', 'GODFRYPHLP.NS', 'GOKULAGRO.NS', 'HBLENGINE.NS', 'HONASA.NS', 'IOC.NS', 'IIFLCAPS.NS', 'IBULLSLTD.NS', 'INDOTECH.NS', 'INDRAMEDCO.NS', 'INDUSTOWER.NS', 'JSLL.NS', 'JYOTICNC.NS', 'KERNEX.NS', 'KRISHANA.NS', 'LLOYDSME.NS', 'LODHA.NS', 'MANORAMA.NS', 'MONARCH.NS', 'MCX.NS', 'MUTHOOTFIN.NS', 'NAZARA.NS', 'NIRLON.NS', 'NMDC.NS', 'NUVAMA.NS', 'KISSHT.NS', 'PNGJL.NS', 'PARADEEP.NS', 'PICCADIL.NS', 'POCL.NS', 'POWERICA.NS', 'PREMEXPLN.NS', 'PREMIERENE.NS', 'REFEX.NS', 'RUBICON.NS', 'SAILIFE.NS', 'SAMBHV.NS', 'SANGHVIMOV.NS', 'SARDAEN.NS', 'SEAMECLTD.NS', 'SEDEMAC.NS', 'SENCO.NS', 'STYL.NS', 'SHAKTIPUMP.NS', 'SHARDACROP.NS', 'SHILCTECH.NS', 'SIGMAADV.NS', 'SKIPPER.NS', 'SMLMAH.NS', 'SPARC.NS', 'SUZLON.NS', 'TARIL.NS', 'TATAELXSI.NS', 'TATATECH.NS', 'THANGAMAYL.NS', 'TRANSRAILL.NS', 'TVSHLTD.NS', 'VMARCIND.NS', 'V2RETAIL.NS', 'MANYAVAR.NS', 'VIKRAMSOLR.NS', 'WAAREEENER.NS', 'WAAREERTL.NS', 'WEBELSOLAR.NS', 'WELCORP.NS', 'WHEELS.NS']

#mystocks
#TICKERS=['ARIS.NS', 'AZAD.NS', 'BLACKBUCK.NS', 'BLUEWATER.NS', 'CGCL.NS', 'CELLECOR.NS', 'COHANCE.NS', 'DABUR.NS', 'DELTACORP.NS', 'DHAMPURSUG.NS', 'EFCIL.NS', 'GENUSPOWER.NS', 'GOCOLORS.NS', 'GOKULAGRO.NS', 'GULPOLY.NS', 'IOC.NS', 'INDOFARM.NS', 'JAYKAY.NS', 'JINDRILL.NS', 'JIOFIN.NS', 'KPEL.NS', 'NETWORK18.NS', 'OPTIEMUS.NS', 'OSELDEVICE.NS', 'PARADEEP.NS', 'POCL.NS', 'PREMIERENE.NS', 'PRICOLLTD.NS', 'REDINGTON.NS', 'RELIANCE.NS', 'SAGILITY.NS', 'MOTHERSON.NS', 'SIGMAADV.NS', 'SONACOMS.NS', 'SUDARSCHEM.NS', 'SUVEN.NS', 'SWANCORP.NS', 'TIL.NS', 'TIMETECHNO.NS', 'VEDL.NS', 'VIKRAN.NS', 'ZTECH.NS', 'ZAGGLE.NS']

#falling numbers
#TICKERS=['AARTIIND.NS', 'AVL.NS', 'AEROFLEX.NS', 'AFCONS.NS', 'AHLUCONT.NS', 'ALIVUS.NS', 'ALOKINDS.NS', 'ARE&M.NS', 'ANURAS.NS', 'ATLANTAELE.NS', 'BALAMINES.NS', 'BASF.NS', 'BAYERCROP.NS', 'BENGALASM.NS', 'BLUEDART.NS', 'CHENNPETRO.NS', 'CAMPUS.NS', 'CAPLIPOINT.NS', 'CASTROLIND.NS', 'CELLO.NS', 'CENTURYPLY.NS', 'CERA.NS', 'CLEAN.NS', 'CYIENT.NS', 'DATAMATICS.NS', 'DCMSHRIRAM.NS', 'DEEPAKFERT.NS', 'AGARWALEYE.NS', 'DYNAMATECH.NS', 'ECLERX.NS', 'EIDPARRY.NS', 'EMIL.NS', 'ETHOSLTD.NS', 'FINEORG.NS', 'GMDCLTD.NS', 'GNFC.NS', 'GRINFRA.NS', 'GSFC.NS', 'GALAXYSURF.NS', 'GPIL.NS', 'GOKEX.NS', 'GOODLUCK.NS', 'GRAPHITE.NS', 'GRAVITA.NS', 'GREENLAM.NS', 'HAPPSTMNDS.NS', 'HAPPYFORGE.NS', 'HEG.NS', 'HNDFDS.NS', 'INDGN.NS', 'INNOVACAP.NS', 'IONEXCHANG.NS', 'IRCON.NS', 'JAMNAAUTO.NS', 'JAYNECOIND.NS', 'JKPAPER.NS', 'JSWHL.NS', 'JUBLINGREA.NS', 'JLHL.NS', 'KAMAHOLD.NS', 'KENNAMET.NS', 'KFINTECH.NS', 'KIRLFER.NS', 'KMEW.NS', 'KPIGREEN.NS', 'KRBL.NS', 'LATENTVIEW.NS', 'LMW.NS', 'MBAPL.NS', 'MAHSCOOTER.NS', 'MGL.NS', 'MASTEK.NS', 'MINDACORP.NS', 'MMTC.NS', 'MOIL.NS', 'NAVA.NS', 'NEOGEN.NS', 'PARKHOSPS.NS', 'PCBL.NS', 'PDSL.NS', 'PNCINFRA.NS', 'PRAJIND.NS', 'PRUDENT.NS', 'RCF.NS', 'RAIN.NS', 'RAINBOW.NS', 'RKFORGE.NS', 'RATNAMANI.NS', 'RHIM.NS', 'RITES.NS', 'SAFARI.NS', 'SARDAEN.NS', 'SAREGAMA.NS', 'SOTL.NS', 'SHARDAMOTR.NS', 'SBCL.NS', 'SKFINDIA.NS', 'SOBHA.NS', 'SONATSOFTW.NS', 'SUNTV.NS', 'SUNFLAG.NS', 'SPLPETRO.NS', 'SURYAROSNI.NS', 'SYNGENE.NS', 'TANLA.NS', 'TATACHEM.NS', 'TBOTEK.NS', 'TIIL.NS', 'TEGA.NS', 'TCI.NS', 'TRIDENT.NS', 'TRIVENI.NS', 'TTKPRESTIG.NS', 'VTL.NS', 'MANYAVAR.NS', 'VINATIORGA.NS', 'YASHO.NS', 'YATHARTH.NS']


#nifty500
#TICKERS=['3MINDIA.NS', 'ABLBL.NS', 'ACE.NS', 'ACUTAAS.NS', 'ATGL.NS', 'ABFRL.NS', 'CPPLUS.NS', 'AFCONS.NS', 'AJANTPHARM.NS', 'ALKEM.NS', 'ARE&M.NS', 'AMBER.NS', 'ANANTRAJ.NS', 'APARINDS.NS', 'APLAPOLLO.NS', 'APOLLOTYRE.NS', 'ASIANPAINT.NS', 'ASTERDM.NS', 'ASTRAL.NS', 'ATUL.NS', 'AUROPHARMA.NS', 'DMART.NS', 'BHEL.NS', 'BPCL.NS', 'BALKRISIND.NS', 'BATAINDIA.NS', 'BAYERCROP.NS', 'BERGEPAINT.NS', 'BIKAJI.NS', 'BSOFT.NS', 'BLUEDART.NS', 'BLUEJET.NS', 'BLUESTARCO.NS', 'FIRSTCRY.NS', 'BRITANNIA.NS', 'CHENNPETRO.NS', 'CARBORUNIV.NS', 'CASTROLIND.NS', 'CEATLTD.NS', 'CEMPRO.NS', 'CGPOWER.NS', 'CHAMBLFERT.NS', 'CIPLA.NS', 'COFORGE.NS', 'COHANCE.NS', 'COLPAL.NS', 'CONCORDBIO.NS', 'COROMANDEL.NS', 'CRISIL.NS', 'CROMPTON.NS', 'CUMMINSIND.NS', 'CYIENT.NS', 'DALBHARAT.NS', 'DEEPAKNTR.NS', 'DIXON.NS', 'DOMS.NS', 'DRREDDY.NS', 'ECLERX.NS', 'ELECON.NS', 'ELGIEQUIP.NS', 'EMAMILTD.NS', 'EMCURE.NS', 'ENDURANCE.NS', 'EXIDEIND.NS', 'FINCABLES.NS', 'FSL.NS', 'FORCEMOT.NS', 'FORTIS.NS', 'GABRIEL.NS', 'GAIL.NS', 'GALLANTT.NS', 'GVT&D.NS', 'GILLETTE.NS', 'GLENMARK.NS', 'MEDANTA.NS', 'GPIL.NS', 'GODREJCP.NS', 'GRANULES.NS', 'GRAVITA.NS', 'FLUOROCHEM.NS', 'HAVELLS.NS', 'HCLTECH.NS', 'HEG.NS', 'HEROMOTOCO.NS', 'HEXT.NS', 'HFCL.NS', 'HSCL.NS', 'HINDUNILVR.NS', 'HINDALCO.NS', 'HINDCOPPER.NS', 'POWERINDIA.NS', 'HYUNDAI.NS', 'IGL.NS', 'INDUSTOWER.NS', 'INFY.NS', 'INOXWIND.NS', 'IPCALAB.NS', 'ITI.NS', 'JBCHEPHARM.NS', 'JINDALSAW.NS', 'JSL.NS', 'JINDALSTEL.NS', 'JSWDULUX.NS', 'JUBLINGREA.NS', 'JUBLPHARMA.NS', 'JWL.NS', 'JYOTICNC.NS', 'KAJARIACER.NS', 'KPIL.NS', 'KEC.NS', 'KEI.NS', 'KPITTECH.NS', 'LTFOODS.NS', 'LTTS.NS', 'LINDEINDIA.NS', 'LLOYDSME.NS', 'LODHA.NS', 'LTM.NS', 'LUPIN.NS', 'MGL.NS', 'MARICO.NS', 'MAXHEALTH.NS', 'MSUMI.NS', 'MPHASIS.NS', 'MRF.NS', 'NATIONALUM.NS', 'NAVA.NS', 'NBCC.NS', 'NCC.NS', 'NESTLEIND.NS', 'NETWEB.NS', 'NEULANDLAB.NS', 'NSLNISP.NS', 'NUVOCO.NS', 'ONGC.NS', 'OLECTRA.NS', 'PAGEIND.NS', 'PATANJALI.NS', 'PERSISTENT.NS', 'PETRONET.NS', 'PGEL.NS', 'PIDILITIND.NS', 'POLYCAB.NS', 'RRKABEL.NS', 'RVNL.NS', 'RAILTEL.NS', 'REDINGTON.NS', 'RHIM.NS', 'SAIL.NS', 'SCI.NS', 'SAGILITY.NS', 'SAILIFE.NS', 'MOTHERSON.NS', 'SCHAEFFLER.NS', 'SHYAMMETL.NS', 'ENRIN.NS', 'SOBHA.NS', 'SONATSOFTW.NS', 'SRF.NS', 'SUNPHARMA.NS', 'SUPREMEIND.NS', 'SPLPETRO.NS', 'SUZLON.NS', 'SWANCORP.NS', 'SWIGGY.NS', 'SYNGENE.NS', 'SYRMA.NS', 'TARIL.NS', 'TATACHEM.NS', 'TATACONSUM.NS', 'TMPV.NS', 'TATATECH.NS', 'TBOTEK.NS', 'TCS.NS', 'TECHM.NS', 'TEGA.NS', 'TENNIND.NS', 'BBTC.NS', 'THERMAX.NS', 'TIMKEN.NS', 'TITAGARH.NS', 'TORNTPHARM.NS', 'TORNTPOWER.NS', 'TRENT.NS', 'TRIDENT.NS', 'TIINDIA.NS', 'ULTRACEMCO.NS', 'UNOMINDA.NS', 'USHAMART.NS', 'VTL.NS', 'VMM.NS', 'VOLTAS.NS', 'WELCORP.NS', 'WELSPUNLIV.NS', 'WHIRLPOOL.NS', 'WOCKPHARMA.NS', 'ZYDUSLIFE.NS', 'ZYDUSWELL.NS']
