# -*- coding: utf-8 -*-
"""
Created on Sun Aug  2 12:28:08 2026

@author: tarun
"""

start_date="2026-01-01"
pf_start_date="2026-07-20"

dist_low=2
dist_high=5
money=1000000
max_positions=7
allocation_per_stock=200000
stoploss=20
initial_capital=1000000
first_day=70

TICKERS=['WEBELSOLAR.NS', 'M&M.NS', 'ASHAPURMIN.NS', 'ADANIPORTS.NS', 'SBILIFE.NS', 'GODFRYPHLP.NS', 'APTUS.NS', 'RUBICON.NS', 'SUZLON.NS', 'EMMVEE.NS', 'KISSHT.NS', 'NUVAMA.NS', 'PARADEEP.NS', 'EBGNG.NS', 'VMARCIND.NS', 'SAMBHV.NS', 'SENCO.NS', 'RELIANCE.NS', 'JYOTICNC.NS', 'SKIPPER.NS', 'NAZARA.NS', 'BANCOINDIA.NS', 'SANGHVIMOV.NS', 'IOC.NS', 'NIRLON.NS', 'SUNPHARMA.NS', 'ICICIBANK.NS', 'ADANIENT.NS', 'ETERNAL.NS', 'EICHERMOT.NS', 'GRSE.NS', 'MARUTI.NS', 'HINDUNILVR.NS', 'INDUSTOWER.NS', 'THANGAMAYL.NS', 'TRENT.NS', 'FINEORG.NS', 'KERNEX.NS', 'REFEX.NS', 'BAJFINANCE.NS', 'HCLTECH.NS', 'SHRIRAMFIN.NS', 'DEEPINDS.NS', 'MUTHOOTFIN.NS', 'MAXHEALTH.NS', 'CRAMC.NS', 'CEMPRO.NS', 'INDIGO.NS', 'TARIL.NS', 'BHARTIARTL.NS', 'ASIANPAINT.NS', 'DPABHUSHAN.NS', 'CEATLTD.NS', 'NESTLEIND.NS', 'ONGC.NS', 'EIEL.NS', 'TATATECH.NS', 'VIKRAMSOLR.NS', 'KRISHANA.NS', 'TCS.NS', 'SEAMECLTD.NS', 'IBULLSLTD.NS', 'SPARC.NS', 'POCL.NS', 'PREMIERENE.NS', 'GALLANTT.NS', 'POWERICA.NS', 'ITC.NS', 'BLS.NS', 'APOLLOHOSP.NS', 'INDRAMEDCO.NS', 'SHILCTECH.NS', 'TATAELXSI.NS', 'CIPLA.NS', 'V2RETAIL.NS', 'DIXON.NS', 'MANYAVAR.NS', 'EPIGRAL.NS', 'PNGJL.NS', 'BAJAJ-AUTO.NS', 'SAILIFE.NS', 'TITAN.NS', 'IIFLCAPS.NS', 'HDFCLIFE.NS', 'SMLMAH.NS', 'SEDEMAC.NS', 'NMDC.NS', 'GOKULAGRO.NS', 'POWERGRID.NS', 'MONARCH.NS', 'COROMANDEL.NS', 'APCOTEXIND.NS', 'JSWSTEEL.NS', 'STYL.NS', 'SHAKTIPUMP.NS', 'BORORENEW.NS', 'WAAREERTL.NS', 'PREMEXPLN.NS', 'ACE.NS', 'WHEELS.NS', 'SHARDACROP.NS', 'CRIZAC.NS', 'CARRARO.NS', 'DRREDDY.NS', 'COALINDIA.NS', 'LODHA.NS', 'NTPC.NS', 'BEL.NS', 'WELCORP.NS', 'INDOTECH.NS', 'HINDALCO.NS', 'KOTAKBANK.NS', 'ULTRACEMCO.NS', 'GENUSPOWER.NS', 'PICCADIL.NS', 'TVSHLTD.NS', 'SBIN.NS', 'SIGMAADV.NS', 'BALUFORGE.NS', 'GANESHHOU.NS', 'MANORAMA.NS', 'TATACONSUM.NS', 'CHENNPETRO.NS', 'JSLL.NS', 'SARDAEN.NS', 'CHALET.NS', 'BAJAJFINSV.NS', 'FORCEMOT.NS', 'UTLSOLAR.NS', 'AXISBANK.NS', 'TRANSRAILL.NS', 'INFY.NS', 'HBLENGINE.NS', 'HDFCBANK.NS', 'BSE.NS', 'JIOFIN.NS', 'WAAREEENER.NS', 'MCX.NS', 'HONASA.NS', 'LLOYDSME.NS', 'WIPRO.NS', 'ARIS.NS', 'BLACKBUCK.NS', 'COHANCE.NS', 'DABUR.NS', 'DELTACORP.NS', 'EFCIL.NS', 'GOCOLORS.NS', 'GULPOLY.NS', 'IOC.NS', 'INDOFARM.NS', 'JIOFIN.NS', 'KPEL.NS', 'NETWORK18.NS', 'PARADEEP.NS', 'RELIANCE.NS', 'SAGILITY.NS', 'MOTHERSON.NS', 'SUVEN.NS', 'SWANCORP.NS', 'TIMETECHNO.NS', 'VEDL.NS', 'VIKRAN.NS', 'ZTECH.NS', 'ZAGGLE.NS']

current_list={'ARIS.NS': '1000', 'BLACKBUCK.NS': '200', 'COHANCE.NS': '3300', 'DABUR.NS': '1000',
              'DELTACORP.NS': '10000', 'EFCIL.NS': '250', 'GOCOLORS.NS': '500', 'GULPOLY.NS': '2000',
              'IOC.NS': '3000', 'INDOFARM.NS': '2000', 'JIOFIN.NS': '7000', 'KPEL.NS': '500',
              'NETWORK18.NS': '29000', 'PARADEEP.NS': '1000', 'RELIANCE.NS': '400', 'SAGILITY.NS': '10000',
              'MOTHERSON.NS': '4725', 'SUVEN.NS': '1000', 'SWANCORP.NS': '2750', 'TIMETECHNO.NS': '5000',
              'VEDL.NS': '1250', 'VIKRAN.NS': '2500', 'ZTECH.NS': '300', 'ZAGGLE.NS': '250'}