# -*- coding: utf-8 -*-
"""
Created on Sun Aug  2 12:28:08 2026

@author: tarun
"""

start_date="2026-01-01"
pf_start_date="2026-07-20"

dist_low=2
dist_high=5
money=1000000
max_positions=7
allocation_per_stock=200000
stoploss=20
initial_capital=1000000
first_day=70

TICKERS=['ACE.NS', 'APCOTEXIND.NS', 'APTUS.NS', 'ARIS.NS', 'ASHAPURMIN.NS', 'AZAD.NS', 'BALUFORGE.NS', 'BANCOINDIA.NS', 'BLACKBUCK.NS', 'BLS.NS', 'BLUEWATER.NS', 'BORORENEW.NS', 'BSE.NS', 
         'CARRARO.NS', 'CEATLTD.NS', 'CELLECOR.NS', 'CEMPRO.NS', 'CGCL.NS', 'CHALET.NS', 'CHENNPETRO.NS', 'COHANCE.NS', 'COROMANDEL.NS', 'CRAMC.NS', 'CRIZAC.NS', 'DABUR.NS', 'DEEPINDS.NS',
         'DELTACORP.NS', 'DHAMPURSUG.NS', 'DIXON.NS', 'DPABHUSHAN.NS', 'EBGNG.NS', 'EFCIL.NS', 'EIEL.NS', 'EMMVEE.NS', 'EPIGRAL.NS', 'FINEORG.NS', 'FISCHER.NS', 'FORCEMOT.NS', 'GALLANTT.NS',
         'GANESHHOU.NS', 'GENUSPOWER.NS', 'GFSTEELS.NS', 'GOCOLORS.NS', 'GODFRYPHLP.NS', 'GOKULAGRO.NS', 'GOODLUCK.NS', 'GRSE.NS', 'GULPOLY.NS', 'HBLENGINE.NS', 'HONASA.NS', 'IBULLSLTD.NS', 
         'IIFLCAPS.NS', 'INDOFARM.NS', 'INDOTECH.NS', 'INDRAMEDCO.NS', 'INDUSTOWER.NS', 'IOC.NS', 'JAYKAY.NS', 'JINDRILL.NS', 'JIOFIN.NS', 'JSLL.NS', 'JYOTICNC.NS', 'KERNEX.NS',
         'KISSHT.NS', 'KPEL.NS', 'KRISHANA.NS', 'LLOYDSME.NS', 'LODHA.NS', 'M&MFIN.NS', 'MANORAMA.NS', 'MANYAVAR.NS', 'MCX.NS', 'MONARCH.NS', 'MOTHERSON.NS', 'MUTHOOTFIN.NS', 'NAHARSPING.NS',
         'NAZARA.NS', 'NETWORK18.NS', 'NIRLON.NS', 'NMDC.NS', 'NUVAMA.NS', 'NYKAA.NS', 'OPTIEMUS.NS', 'OSELDEVICE.NS', 'PARADEEP.NS', 'PICCADIL.NS', 'PNGJL.NS', 
         'POCL.NS', 'POLICYBZR.NS', 'POWERICA.NS', 'PREMEXPLN.NS', 'PREMIERENE.NS', 'PRICOLLTD.NS', 'REDINGTON.NS', 'REFEX.NS', 'RELIANCE.NS', 'RUBICON.NS', 'SAGILITY.NS', 
         'SAILIFE.NS', 'SAMBHV.NS', 'SANDESH.NS', 'SANGHVIMOV.NS', 'SARDAEN.NS', 'SEAMECLTD.NS', 'SEDEMAC.NS', 'SENCO.NS', 'SENORES.NS', 'SHAKTIPUMP.NS', 'SHARDACROP.NS',
         'SHILCTECH.NS', 'SIGMAADV.NS', 'SKIPPER.NS', 'SMLMAH.NS', 'SONACOMS.NS', 'SOTL.NS', 'SPARC.NS', 'STYL.NS', 'SUDARSCHEM.NS', 'SUVEN.NS', 'SUZLON.NS', 'SWANCORP.NS', 
         'TARIL.NS', 'TATAELXSI.NS', 'TATATECH.NS', 'THANGAMAYL.NS', 'TIL.NS', 'TIMETECHNO.NS', 'TRANSRAILL.NS', 'TVSHLTD.NS', 'TVSMOTOR.NS', 'UNIPARTS.NS', 'UTLSOLAR.NS',
         'V2RETAIL.NS', 'VEDL.NS', 'VIKRAMSOLR.NS', 'VIKRAN.NS', 'VMARCIND.NS', 'WAAREEENER.NS', 'WAAREERTL.NS', 'WEBELSOLAR.NS', 'WELCORP.NS', 'WHEELS.NS', 'ZAGGLE.NS', 'ZTECH.NS',
         'META.BO']



current_list={'ARIS.NS': '1000', 'BLACKBUCK.NS': '200', 'COHANCE.NS': '3300', 'DABUR.NS': '1000',
              'DELTACORP.NS': '10000', 'EFCIL.NS': '250', 'GOCOLORS.NS': '500', 'GULPOLY.NS': '2000',
              'IOC.NS': '3000', 'INDOFARM.NS': '2000', 'JIOFIN.NS': '7000', 'KPEL.NS': '500',
              'NETWORK18.NS': '29000', 'PARADEEP.NS': '1000', 'RELIANCE.NS': '400', 'SAGILITY.NS': '10000',
              'MOTHERSON.NS': '4725', 'SUVEN.NS': '1000', 'SWANCORP.NS': '2750', 'TIMETECHNO.NS': '5000',
              'VEDL.NS': '1250', 'VIKRAN.NS': '2500', 'ZTECH.NS': '300', 'ZAGGLE.NS': '250'}